import groovy.transform.Field


@Library('cribl-jenkins')_


final String WORKSPACE_PATH = '/home/jenkins/agent/workspace'

pipeline {
  agent {
    kubernetes {
      cloud 'k8s-devops'
      yamlFile 'ci/cribl/jenkins/podspec.yml'
      defaultContainer 'builder'
      customWorkspace WORKSPACE_PATH
      workingDir WORKSPACE_PATH
    }
  }

  options {
    ansiColor('xterm')
    buildDiscarder(logRotator(daysToKeepStr: '21'))
    copyArtifactPermission("*")
    disableRestartFromStage()
  }

  stages {
    stage('Build ClickHouse') {
      steps {
        script {
          // TODO: setup script?
          sh "git config --global --add safe.directory /home/jenkins/agent/workspace"
          sh "git submodule update --init"
          sh "cmake -S . -B build -DNO_ARMV81_OR_HIGHER=1"
          sh "cmake --build build -DNO_ARMV81_OR_HIGHER=1"
          utils.s3Archive([
            sourceFile: 'build/**/*'
          ])
        }
      }
    }
  }
}